# Generated by Django 5.1.4 on 2026-03-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+7 (495) 123-45-67', max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(default='info@d4tech.ru', max_length=254, verbose_name='Email')),
                ('address', models.CharField(default='г. Москва, ул. D4, д. 1', max_length=200, verbose_name='Адрес')),
                ('website', models.CharField(default='d4tech.ru', max_length=100, verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
    ]
